version: '3'

services:
  gcc:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: game-theory-gcc
    volumes:
      - .:/work/game-theory
    restart: always
    tty: true
